apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: service-monitor-mlab02
  namespace: mlab02
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - mlab02
  selector:
    matchLabels:
      app: myapp-mlab02
  endpoints:
  - port: "http"
    path: "/actuator/prometheus"
    interval: 15s