apiVersion: v1
kind: Service
metadata:
  name: mlab02-service
  namespace: mlab02
  labels:
    app: myapp-mlab02
spec:
  ports:
  - name: "http"
    port: 8081
    targetPort: 8080
  selector:
    app: myapp-mlab02