apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: development
  labels:
    app: myapp-development
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: myapp-development